<?php
/**
 * Created by PhpStorm.
 * User: Nic
 * Date: 14/08/2018
 * Time: 15:16
 */

namespace License\Controller;

use License\Service\LicenseService;
use Zend\Mvc\Controller\AbstractRestfulController;

/**
 * Class LicenseApiController
 * @package License\Controller
 */
class LicenseApiController extends AbstractRestfulController
{
    /** @var LicenseService $licenseService */
    private $licenseService;

    /**
     * LicenseApiController constructor.
     * @param LicenseService $licenseService
     */
    public function __construct(LicenseService $licenseService)
    {
        $this->licenseService = $licenseService;
    }

    public function getList()
    {
        return parent::getList(); // TODO: Change the autogenerated stub
    }

    public function get($id)
    {
        return parent::get($id); // TODO: Change the autogenerated stub
    }
}